### ISSUE TITLE
Wrong font-roboto dependency

### ISSUE THREAD

**Issue by Inrego** [expandjs/mat-typography#1]
Hey there.

Recently you updated the font-roboto dependency to 1.0.0
However, you forgot that the font-roboto 1.0.0 is no longer in Polymer, but PolymerElements

So instead of Polymer/font-roboto#^1.0.0 it should be PolymerElements/font-roboto#1.0.0

This error is causing installation failures through bower

**Comment by Pupix** [comment]
Thanks for the report, it's been fixed.
